### ISSUE TITLE
Album name

### ISSUE THREAD

**Issue by AdiletAbylov** [ndac-todoroki/elixir-id3#5]
There is no album name in `ID3.Tag`.
Is this bug or feature? 😅

**Comment by ndac-todoroki** [comment]
`id3` is still a WIP... It implements feature which I want to use first! :grin: 
Although I am not currently using `id3` further than the current features, I'd be happy to implement it.
(Contributions are welcomed too!)

Currently the COVID-IV is messing up my work (when I just moved to a new home!! :disappointed:), it _may_ take some time for me to do this. I'll try my best.
thanks,

**Comment by gen1321** [comment]
even tho I have no clue how to write rust I think I will be able to do it, stay safe
